### ISSUE TITLE
bad marshal data using models H and J 

### ISSUE THREAD

**Issue by MSnelders** [devanshkv/fetch#21]
I've installed FETCH (and _your_) on a fairly old machine (with no GPU) in a new conda environment. All seems to go well except when I use models H and J. 

**To Reproduce**
In the directory where the h5 files are:
```console
(fetchenv2) snelders@dop263:~/testfetch/cand$ ls *h5 -l
-rw-r--r-- 1 snelders 9000 359255 nov 15 17:00 cand_tstart_58682.620316710374_tcand_2.0288800_dm_475.28400_snr_13.92710.h5
-rw-r--r-- 1 snelders 9000 359751 nov 15 17:00 cand_tstart_58682.620316710374_tcand_2.0288800_dm_475.28400_snr_16.81280.h5
-rw-r--r-- 1 snelders 9000 357159 nov 15 17:00 cand_tstart_58682.620316710374_tcand_2.0288800_dm_475.28400_snr_18.66470.h5
```

```console
predict.py -m h -g -1 -c .
```

```console
2021-11-16 08:55:37.059175: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-11-16 08:55:40,352 - get_model -fetch.utils - INFO - Getting model h
2021-11-16 08:55:47.978135: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-11-16 08:55:47.978571: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-11-16 08:55:47.978598: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-11-16 08:55:47.978633: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (dop263): /proc/driver/nvidia/version does not exist
2021-11-16 08:55:47.978866: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-11-16 08:55:47.983296: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Traceback (most recent call last):
  File "/export/astron/snelders/anaconda3/envs/fetchenv2/bin/predict.py", line 4, in <module>
    __import__('pkg_resources').run_script('fetch==0.2.0', 'predict.py')
  File "/export/astron/snelders/anaconda3/envs/fetchenv2/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/export/astron/snelders/anaconda3/envs/fetchenv2/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/misc/astron/snelders/anaconda3/envs/fetchenv2/lib/python3.9/site-packages/fetch-0.2.0-py3.9.egg/EGG-INFO/scripts/predict.py", line 79, in <module>
    model = get_model(args.model)
  File "/export/astron/snelders/anaconda3/envs/fetchenv2/lib/python3.9/site-packages/fetch-0.2.0-py3.9.egg/fetch/utils.py", line 92, in get_model
    model = model_from_yaml(y.read())
  File "/export/astron/snelders/anaconda3/envs/fetchenv2/lib/python3.9/site-packages/tensorflow/python/keras/saving/model_config.py", line 105, in model_from_yaml
    return deserialize(config, custom_objects=custom_objects)
  File "/export/astron/snelders/anaconda3/envs/fetchenv2/lib/python3.9/site-packages/tensorflow/python/keras/layers/serialization.py", line 173, in deserialize
    return generic_utils.deserialize_keras_object(
  File "/export/astron/snelders/anaconda3/envs/fetchenv2/lib/python3.9/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 354, in deserialize_keras_object
    return cls.from_config(
  File "/export/astron/snelders/anaconda3/envs/fetchenv2/lib/python3.9/site-packages/tensorflow/python/keras/engine/training.py", line 2261, in from_config
    return functional.Functional.from_config(
  File "/export/astron/snelders/anaconda3/envs/fetchenv2/lib/python3.9/site-packages/tensorflow/python/keras/engine/functional.py", line 668, in from_config
    input_tensors, output_tensors, created_layers = reconstruct_from_config(
  File "/export/astron/snelders/anaconda3/envs/fetchenv2/lib/python3.9/site-packages/tensorflow/python/keras/engine/functional.py", line 1275, in reconstruct_from_config
    process_layer(layer_data)
  File "/export/astron/snelders/anaconda3/envs/fetchenv2/lib/python3.9/site-packages/tensorflow/python/keras/engine/functional.py", line 1257, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/export/astron/snelders/anaconda3/envs/fetchenv2/lib/python3.9/site-packages/tensorflow/python/keras/layers/serialization.py", line 173, in deserialize
    return generic_utils.deserialize_keras_object(
  File "/export/astron/snelders/anaconda3/envs/fetchenv2/lib/python3.9/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 354, in deserialize_keras_object
    return cls.from_config(
  File "/export/astron/snelders/anaconda3/envs/fetchenv2/lib/python3.9/site-packages/tensorflow/python/keras/engine/training.py", line 2261, in from_config
    return functional.Functional.from_config(
  File "/export/astron/snelders/anaconda3/envs/fetchenv2/lib/python3.9/site-packages/tensorflow/python/keras/engine/functional.py", line 668, in from_config
    input_tensors, output_tensors, created_layers = reconstruct_from_config(
  File "/export/astron/snelders/anaconda3/envs/fetchenv2/lib/python3.9/site-packages/tensorflow/python/keras/engine/functional.py", line 1275, in reconstruct_from_config
    process_layer(layer_data)
  File "/export/astron/snelders/anaconda3/envs/fetchenv2/lib/python3.9/site-packages/tensorflow/python/keras/engine/functional.py", line 1257, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/export/astron/snelders/anaconda3/envs/fetchenv2/lib/python3.9/site-packages/tensorflow/python/keras/layers/serialization.py", line 173, in deserialize
    return generic_utils.deserialize_keras_object(
  File "/export/astron/snelders/anaconda3/envs/fetchenv2/lib/python3.9/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 354, in deserialize_keras_object
    return cls.from_config(
  File "/export/astron/snelders/anaconda3/envs/fetchenv2/lib/python3.9/site-packages/tensorflow/python/keras/layers/core.py", line 1019, in from_config
    function = cls._parse_function_from_config(
  File "/export/astron/snelders/anaconda3/envs/fetchenv2/lib/python3.9/site-packages/tensorflow/python/keras/layers/core.py", line 1071, in _parse_function_from_config
    function = generic_utils.func_load(
  File "/export/astron/snelders/anaconda3/envs/fetchenv2/lib/python3.9/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 457, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)
```

**Expected behavior**
```console
predict.py -m a -g -1 -c .
`2021-11-16 08:53:16.533682: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-11-16 08:53:21,303 - get_model -fetch.utils - INFO - Getting model a
2021-11-16 08:53:24.693684: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-11-16 08:53:24.695914: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-11-16 08:53:24.695944: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-11-16 08:53:24.695976: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (dop263): /proc/driver/nvidia/version does not exist
2021-11-16 08:53:24.696268: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-11-16 08:53:24.700161: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
/export/astron/snelders/anaconda3/envs/fetchenv2/lib/python3.9/site-packages/tensorflow/python/keras/engine/training.py:1905: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  warnings.warn('`Model.predict_generator` is deprecated and '
2021-11-16 08:53:31.605966: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-11-16 08:53:31.607097: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2400190000 Hz
1/1 [==============================] - 5s 5s/step
```

```console
(fetchenv2) snelders@dop263:~/testfetch/cand$ cat results_a.csv 
,candidate,probability,label
0,./cand_tstart_58682.620316710374_tcand_2.0288800_dm_475.28400_snr_13.92710.h5,1.0,1.0
1,./cand_tstart_58682.620316710374_tcand_2.0288800_dm_475.28400_snr_16.81280.h5,1.0,1.0
2,./cand_tstart_58682.620316710374_tcand_2.0288800_dm_475.28400_snr_18.66470.h5,1.0,1.0
```

I expected that all models would work or that none of the models would work. 
Info about environment:
`conda list`
<details>
<summary>Click to collapse.</summary>
<p>

```console
(fetchenv2) snelders@dop263:~/testfetch/cand$ conda list
# packages in environment at /export/astron/snelders/anaconda3/envs/fetchenv2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
_tflow_select             2.1.0                       gpu  
absl-py                   0.13.0           py39h06a4308_0  
aiohttp                   3.7.4.post0      py39h7f8727e_2  
astor                     0.8.1            py39h06a4308_0  
astropy                   4.3.1            py39h09021b7_0  
astunparse                1.6.3                      py_0  
async-timeout             3.0.1            py39h06a4308_0  
attrs                     21.2.0             pyhd3eb1b0_0  
blas                      1.0                         mkl  
blinker                   1.4              py39h06a4308_0  
blosc                     1.21.0               h8c45485_0  
bottleneck                1.3.2            py39hdd57654_1  
brotli                    1.0.9                he6710b0_2  
brotlipy                  0.7.0           py39h27cfd23_1003  
brunsli                   0.1                  h2531618_0  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.17.1               h27cfd23_0  
ca-certificates           2021.10.26           h06a4308_2  
cachetools                4.2.2              pyhd3eb1b0_0  
certifi                   2021.10.8        py39h06a4308_0  
cffi                      1.14.6           py39h400218f_0  
cfitsio                   3.470                hf0d0db6_6  
chardet                   4.0.0           py39h06a4308_1003  
charls                    2.2.0                h2531618_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.3              pyhd3eb1b0_0  
cloudpickle               2.0.0              pyhd3eb1b0_0  
colorama                  0.4.4              pyhd3eb1b0_0  
commonmark                0.9.1              pyhd3eb1b0_0  
coverage                  5.5              py39h27cfd23_2  
cryptography              3.4.8            py39hd23ed53_0  
cudatoolkit               10.1.243             h6bb024c_0  
cudnn                     7.6.5                cuda10.1_0  
cupti                     10.1.168                      0  
cycler                    0.10.0           py39h06a4308_0  
cython                    0.29.24          py39hdbfa776_0  
cytoolz                   0.11.0           py39h27cfd23_0  
dask-core                 2021.10.0          pyhd3eb1b0_0  
dataclasses               0.8                pyh6d0b6a4_7  
dbus                      1.13.18              hb2f20db_0  
expat                     2.4.1                h2531618_2  
fetch                     0.2.0                    pypi_0    pypi
fontconfig                2.13.1               h6c09931_0  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.11.0               h70c0345_0  
fsspec                    2021.10.1          pyhd3eb1b0_0  
future                    0.18.2           py39h06a4308_1  
gast                      0.4.0              pyhd3eb1b0_0  
giflib                    5.2.1                h7b6447c_0  
glib                      2.69.1               h5202010_0  
google-auth               1.33.0             pyhd3eb1b0_0  
google-auth-oauthlib      0.4.4              pyhd3eb1b0_0  
google-pasta              0.2.0              pyhd3eb1b0_0  
grpcio                    1.36.1           py39h2157cd5_1  
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
h5py                      2.10.0           py39hec9cf62_0  
hdf5                      1.10.6               hb1b8bf9_0  
icu                       58.2                 he6710b0_3  
idna                      3.2                pyhd3eb1b0_0  
imagecodecs               2021.8.26        py39h4cda21f_0  
imageio                   2.9.0              pyhd3eb1b0_0  
importlib-metadata        4.8.1            py39h06a4308_0  
intel-openmp              2021.4.0          h06a4308_3561  
jpeg                      9d                   h7f8727e_0  
jxrlib                    1.1                  h7b6447c_2  
keras-preprocessing       1.1.2              pyhd3eb1b0_0  
kiwisolver                1.3.1            py39h2531618_0  
krb5                      1.19.2               hac12032_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.35.1               h7274673_9  
lerc                      3.0                  h295c915_0  
libaec                    1.0.4                he6710b0_1  
libcurl                   7.78.0               h0b77cf5_0  
libdeflate                1.8                  h7f8727e_5  
libedit                   3.1.20210910         h7f8727e_0  
libev                     4.33                 h7f8727e_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   9.3.0               h5101ec6_17  
libllvm11                 11.1.0               h3826bc1_0  
libnghttp2                1.41.0               hf8bcb03_2  
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.17.2               h4ff587b_1  
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtiff                   4.2.0                h85742a9_0  
libuuid                   1.0.3                h7f8727e_2  
libwebp                   1.2.0                h89dd481_0  
libwebp-base              1.2.0                h27cfd23_0  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.12               h03d6c58_0  
libzopfli                 1.0.3                he6710b0_0  
llvmlite                  0.37.0           py39h295c915_1  
locket                    0.2.1            py39h06a4308_1  
lz4-c                     1.9.3                h295c915_1  
markdown                  3.3.4            py39h06a4308_0  
matplotlib                3.4.3            py39h06a4308_0  
matplotlib-base           3.4.3            py39hbbc1b5f_0  
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py39h7f8727e_0  
mkl_fft                   1.3.1            py39hd3c417c_0  
mkl_random                1.2.2            py39h51133e4_0  
multidict                 5.1.0            py39h27cfd23_2  
munkres                   1.1.4                      py_0  
ncurses                   6.3                  h7f8727e_2  
networkx                  2.6.3              pyhd3eb1b0_0  
numba                     0.54.1           py39h51133e4_0  
numexpr                   2.7.3            py39h22e1b3c_1  
numpy                     1.20.3           py39hf144106_0  
numpy-base                1.20.3           py39h74d4b33_0  
oauthlib                  3.1.1              pyhd3eb1b0_0  
olefile                   0.46               pyhd3eb1b0_0  
openjpeg                  2.4.0                h3ad879b_0  
openssl                   1.1.1l               h7f8727e_0  
opt_einsum                3.3.0              pyhd3eb1b0_1  
packaging                 21.0               pyhd3eb1b0_0  
pandas                    1.3.4            py39h8c16a72_0  
partd                     1.2.0              pyhd3eb1b0_0  
pcre                      8.45                 h295c915_0  
pillow                    8.4.0            py39h5aabda8_0  
pip                       21.2.4           py39h06a4308_0  
protobuf                  3.17.2           py39h295c915_0  
pyasn1                    0.4.8              pyhd3eb1b0_0  
pyasn1-modules            0.2.8                      py_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyerfa                    2.0.0            py39h27cfd23_0  
pygments                  2.10.0             pyhd3eb1b0_0  
pyjwt                     2.1.0            py39h06a4308_0  
pyopenssl                 21.0.0             pyhd3eb1b0_1  
pyparsing                 3.0.4              pyhd3eb1b0_0  
pyqt                      5.9.2            py39h2531618_6  
pysocks                   1.7.1            py39h06a4308_0  
python                    3.9.7                h12debd9_1  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-flatbuffers        2.0                pyhd3eb1b0_0  
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.3             pyhd3eb1b0_0  
pywavelets                1.1.1            py39h6323ea4_4  
pyyaml                    6.0              py39h7f8727e_1  
qt                        5.9.7                h5867ecd_1  
readline                  8.1                  h27cfd23_0  
requests                  2.26.0             pyhd3eb1b0_0  
requests-oauthlib         1.3.0                      py_0  
rich                      10.13.0          py39hf3d152e_0    conda-forge
rsa                       4.7.2              pyhd3eb1b0_1  
scikit-image              0.18.3           py39h51133e4_0  
scipy                     1.7.1            py39h292c36d_2  
setuptools                58.0.4           py39h06a4308_0  
sip                       4.19.13          py39h2531618_0  
six                       1.16.0             pyhd3eb1b0_0  
snappy                    1.1.8                he6710b0_0  
sqlite                    3.36.0               hc218d9a_0  
tbb                       2021.4.0             hd09550d_0  
tensorboard               2.4.0              pyhc547734_0  
tensorboard-plugin-wit    1.6.0                      py_0  
tensorflow                2.4.1           gpu_py39h8236f22_0  
tensorflow-base           2.4.1           gpu_py39h29c2da4_0  
tensorflow-estimator      2.6.0              pyh7b7c402_0  
tensorflow-gpu            2.4.1                h30adc30_0  
termcolor                 1.1.0            py39h06a4308_1  
tifffile                  2021.7.2           pyhd3eb1b0_2  
tk                        8.6.11               h1ccaba5_0  
toolz                     0.11.2             pyhd3eb1b0_0  
tornado                   6.1              py39h27cfd23_0  
typing-extensions         3.10.0.2             hd3eb1b0_0  
typing_extensions         3.10.0.2           pyh06a4308_0  
tzdata                    2021e                hda174b7_0  
urllib3                   1.26.7             pyhd3eb1b0_0  
werkzeug                  2.0.2              pyhd3eb1b0_0  
wheel                     0.37.0             pyhd3eb1b0_1  
wrapt                     1.12.1           py39he8ac12f_1  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
yarl                      1.6.3            py39h27cfd23_0  
your                      0.6.6                    pypi_0    pypi
zfp                       0.5.5                h2531618_6  
zipp                      3.6.0              pyhd3eb1b0_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.9                haebb681_0
```

</p>
</details>  

When I run all models I get the same message for models A, B, C, D, E, F, G, I, K. With these models the results_?.csv is also created correctly. 
Models H and J produce the same error message and no results_?.csv is made. 

Any ideas why this happens? For now I am just skipping models H and J, but I am curious why the other models would work and these wouldn't.

**Comment by devanshkv** [comment]
Sorry @MSnelders but we won't be working towards fixing this for now.

**Comment by MSnelders** [comment]
Hi @devanshkv , no worries! I will just omit models H and J for now.
