### ISSUE TITLE
URL failure

### ISSUE THREAD

**Issue by Shinnnosuke2** [devanshkv/fetch#24]
Hi,

When I ran predict.py, I got the following error.
This is the same error as the case of #23.

Traceback (most recent call last):
  File "/home/shisano/anaconda3/envs/fetch_env/bin/predict.py", line 4, in <module>
    __import__('pkg_resources').run_script('fetch==0.2.0', 'predict.py')
  File "/home/shisano/anaconda3/envs/fetch_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/shisano/anaconda3/envs/fetch_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/KUMA/kuma1/shisano/anaconda3/envs/fetch_env/lib/python3.7/site-packages/fetch-0.2.0-py3.7.egg/EGG-INFO/scripts/predict.py", line 79, in <module>
    model = get_model(args.model)
  File "/home/shisano/anaconda3/envs/fetch_env/lib/python3.7/site-packages/fetch-0.2.0-py3.7.egg/fetch/utils.py", line 103, in get_model
    hash_algorithm="md5",
  File "/home/shisano/anaconda3/envs/fetch_env/lib/python3.7/site-packages/tensorflow/python/keras/utils/data_utils.py", line 260, in get_file
    raise Exception(error_msg.format(origin, e.code, e.msg))
Exception: URL fetch failure on http://psrpop.phys.wvu.edu/download.php?val=ft_DenseNet121_2_dt_Xception_13_256.h5: 502 -- Bad Gateway

Is the link offline again now?

**Comment by devanshkv** [comment]
Thanks to [nategarver-daniels](https://github.com/nategarver-daniels), it is fixed now.
