### ISSUE TITLE
FETCH may be completely broke

### ISSUE THREAD

**Issue by aweaver1fandm** [devanshkv/fetch#39]
I just tried to run FETCH and it seems like the server that holds the models is no longer available.  Here
is the output:

File "/opt/apps/spack/python-3.10.14-3s2bi75/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/apps/spack/fetch-tf2-fymf6zo/bin/predict.py", line 79, in <module>
    model = get_model(args.model)
  File "/opt/apps/spack/fetch-tf2-fymf6zo/lib/python3.10/site-packages/fetch/utils.py", line 98, in get_model
    weights = get_file(
  File "/opt/apps/spack/py-keras-2.8.0-xl2halo/lib/python3.10/site-packages/keras/utils/data_utils.py", line 279, in get_file
    raise Exception(error_msg.format(origin, e.code, e.msg))
Exception: URL fetch failure on http://psrpop.phys.wvu.edu/download.php?val=ft_DenseNet121_2_dt_Xception_13_256.h5: 502 -- Bad Gateway

**Comment by devanshkv** [comment]
I've started an internal thread to resolve this, will keep you posted.

**Comment by aweaver1fandm** [comment]
As an aside, a few months ago I did manually download the models so if necessary I have them

**Comment by devanshkv** [comment]
Thanks, we have the weights, the vm which was hosting the url needs to be replaced. That work is currently underway.

**Comment by raiffhugo** [comment]
Hello @devanshkv and @aweaver1fandm,

I am part of the BINGO collaboration and we are using FETCH for data analysis in our project. If possible, could either of you share the AI model weights or provide an alternative link for downloading them? This would greatly assist us in continuing our work while the hosting issue is being resolved.

Thank you very much for your help!

**Comment by aweaver1fandm** [comment]
I have posted a version of the models I downloaded before the WVU server went down.  They are available through Globus here:
https://app.globus.org/file-manager?origin_id=d8783496-59e9-4b16-be52-dfca6deea962&origin_path=%2F

You will probably need a Globus logon to get these if you don't have one already.  If you don't have one, you can get a login free (read Step 1 of this intro https://docs.globus.org/guides/tutorials/manage-files/transfer-files/)

You will probably need to modify the FETCH code to use a local copy of a model rather than access it over the internet.  Also,  I am not the original person who developed FETCH.  I am assuming these models are up-to-date but I cannot guarantee that.

If you have trouble accessing the model files, just update this issue

**Comment by raiffhugo** [comment]
Thank you for sharing the model weights and the Globus link. This will be very helpful for our work with FETCH.

I appreciate your assistance.

**Comment by aamod-wick** [comment]
Hi @devanshkv I think we can for now import the model using tf libraries using param listed in fetch/fetch/models right ? I am using a fix doing that exactly right now for personal use . Maybe i can push here too if you dont mind .

**Comment by devanshkv** [comment]
Fixed with #43
