### ISSUE TITLE
 unsupported operand type(s) for ** or pow(): 'str' and 'int'

### ISSUE THREAD

**Issue by SanatMoharir** [devanshkv/fetch#7]
Hi @devanshkv @KshitijAggarwal 
Hey I just tried to run the code but there are some problems happening whenever I run:

candmaker.py --frequency_size 256 --time_size 256 --cand_param_file cands.csv --plot --fout /data/candidates/

I am getting:

Traceback (most recent call last):
  File "/home/sanat/anaconda3/envs/testenv/bin/candmaker.py", line 4, in <module>
    __import__('pkg_resources').run_script('fetch==0.1.8', 'candmaker.py')
  File "/home/sanat/anaconda3/envs/testenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/sanat/anaconda3/envs/testenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/home/sanat/anaconda3/envs/testenv/lib/python3.6/site-packages/fetch-0.1.8-py3.6.egg/EGG-INFO/scripts/candmaker.py", line 130, in <module>
    [row['fil_file'], row['snr'], row['width'] **2, row['dm'], row['label'], row['stime'],
TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'int'

And can you please provide the cands.csv file so I can test the code? And please can you please help me with running the code?

Thanks, in advance !!!!

**Comment by SanatMoharir** [comment]
And what are the versions of all packages that are used in this project?

**Comment by devanshkv** [comment]
@SanatMoharir checkout 6b7c600ec0c19c6b599fed9f88d567732eb498ae.

**Comment by devanshkv** [comment]
@SanatMoharir I have added the yaml files, checkout f9f385a.
